package leonil.sulude.catalog.pact;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.StateChangeAction;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import leonil.sulude.catalog.integration.AbstractIntegrationTest;
import leonil.sulude.catalog.model.ServiceCategory;
import leonil.sulude.catalog.model.ServiceOffer;
import leonil.sulude.catalog.model.ServiceResource;
import leonil.sulude.catalog.repository.ServiceOfferRepository;
import leonil.sulude.catalog.repository.ServiceResourceRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Provider-side verification that ServiceResourceController's /api/resources endpoints
 * actually satisfy the HTTP contract booking-service depends on (CatalogClient), per the
 * pact file generated by CatalogServiceHttpPactTest in booking-service.
 *
 * IT suffix (not Test) --- this needs real Testcontainers Postgres via AbstractIntegrationTest,
 * so it must run under Failsafe (mvn verify), not Surefire (mvn test), like every other
 * integration test in this service.
 *
 * No Pact Broker is set up yet, so the pact file is committed here under
 * src/test/resources/pacts rather than fetched remotely. Regenerate it by running
 * CatalogServiceHttpPactTest in booking-service and re-copying its output whenever the
 * consumer contract changes.
 */
@Provider("catalog-service")
@PactFolder("src/test/resources/pacts")
class CatalogServiceHttpPactVerificationIT extends AbstractIntegrationTest {

    // must match the literal example path baked into the pact file by CatalogServiceHttpPactTest —
    // request paths are replayed verbatim during verification, they are not regex-matched
    private static final UUID RESOURCE_ID = UUID.fromString("e2b1a7d0-1a2b-4c3d-8e9f-0a1b2c3d4e5f");

    @LocalServerPort
    private int port;

    @Autowired
    private ServiceOfferRepository offerRepository;

    @Autowired
    private ServiceResourceRepository resourceRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }

    @BeforeEach
    void before(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @State("resource e2b1a7d0-1a2b-4c3d-8e9f-0a1b2c3d4e5f exists")
    void resourceExists() {
        ServiceOffer offer = offerRepository.save(new ServiceOffer(
                "Hair Salon", "Salon services", ServiceCategory.BEAUTY, "Jane's Salon", "Lisbon"));

        // inserted directly via JDBC, bypassing Hibernate's UUID generator, so the row gets
        // exactly the id the pact's request path expects rather than a random generated one
        jdbcTemplate.update(
                "INSERT INTO service_resources (id, offer_id, name, price, duration_in_minutes, active) " +
                        "VALUES (?, ?, ?, ?, ?, ?)",
                RESOURCE_ID, offer.getId(), "Haircut Deluxe", new BigDecimal("35.00"), 45, true);
    }

    @State(value = "resource e2b1a7d0-1a2b-4c3d-8e9f-0a1b2c3d4e5f exists", action = StateChangeAction.TEARDOWN)
    void resourceExistsTeardown() {
        jdbcTemplate.update("DELETE FROM service_resources WHERE id = ?", RESOURCE_ID);
    }

    @State("no resource exists with id e2b1a7d0-1a2b-4c3d-8e9f-0a1b2c3d4e5f")
    void noResourceExists() {
        jdbcTemplate.update("DELETE FROM service_resources WHERE id = ?", RESOURCE_ID);
    }

    @State("at least one active resource exists")
    void atLeastOneActiveResourceExists() {
        ServiceOffer offer = offerRepository.save(new ServiceOffer(
                "Hair Salon", "Salon services", ServiceCategory.BEAUTY, "Jane's Salon", "Lisbon"));

        ServiceResource resource = new ServiceResource();
        resource.setOffer(offer);
        resource.setName("Haircut Deluxe");
        resource.setPrice(new BigDecimal("35.00"));
        resource.setDurationInMinutes(45);
        resource.setActive(true);
        resourceRepository.save(resource);
    }
}
