package leonil.sulude.catalog.pact;

import au.com.dius.pact.provider.MessageAndMetadata;
import au.com.dius.pact.provider.PactVerifyProvider;
import au.com.dius.pact.provider.junit5.MessageTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import leonil.sulude.catalog.dto.ResourceEventDTO;
import leonil.sulude.catalog.integration.AbstractIntegrationTest;
import leonil.sulude.catalog.messaging.ResourceEventProducer;
import leonil.sulude.catalog.messaging.ResourceEventType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Provider-side verification that ResourceEventProducer actually publishes messages on
 * "catalog.resource.events" matching the message contract booking-service depends on
 * (ResourceEventConsumer), per the pact file generated by
 * CatalogResourceEventsMessagePactTest in booking-service.
 *
 * IT suffix (not Test) --- this needs a real Testcontainers Kafka broker via
 * AbstractIntegrationTest, so it must run under Failsafe (mvn verify), not Surefire
 * (mvn test), like every other integration test in this service.
 *
 * Unlike a typical message-pact provider test that hand-builds the expected JSON, this one
 * calls the real producer and reads back the real bytes from a real (Testcontainers) Kafka
 * broker — proving the actual Spring Kafka JsonSerializer wire format satisfies the contract,
 * not just that the DTO's field names line up.
 *
 * No Pact Broker is set up yet, so the pact file is committed here under
 * src/test/resources/pacts rather than fetched remotely. Regenerate it by running
 * CatalogResourceEventsMessagePactTest in booking-service and re-copying its output whenever
 * the consumer contract changes.
 */
@Provider("catalog-service-kafka-resource-events")
@PactFolder("src/test/resources/pacts")
class ResourceEventsMessagePactVerificationIT extends AbstractIntegrationTest {

    private static final String TOPIC = "catalog.resource.events";

    @Autowired
    private ResourceEventProducer resourceEventProducer;

    @Autowired
    private ObjectMapper objectMapper;

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }

    @BeforeEach
    void before(PactVerificationContext context) {
        context.setTarget(new MessageTestTarget());
    }

    // no DB/broker setup needed — verifyResourceCreatedEvent() below does the real work of
    // publishing and reading back the message. This no-op only exists because pact-jvm
    // requires a matching @State method for every providerState declared in the pact file.
    @State("a resource was created in Catalog")
    void resourceWasCreatedInCatalog() {
    }

    @PactVerifyProvider("a resource created event")
    public MessageAndMetadata verifyResourceCreatedEvent() throws Exception {
        UUID resourceId = UUID.randomUUID();
        resourceEventProducer.publish(new ResourceEventDTO(
                ResourceEventType.RESOURCE_CREATED,
                resourceId,
                "Haircut Deluxe",
                new BigDecimal("35.00"),
                45,
                true));

        // the topic may contain events from other tests sharing the same container —
        // find the one this call actually published, same approach as ResourceCreationEventIT
        List<String> messages = consumeMessages(TOPIC, Duration.ofSeconds(10));
        String json = messages.stream()
                .filter(m -> matchesResource(m, resourceId))
                .findFirst()
                .orElseThrow(() -> new AssertionError("No Kafka event found for resource " + resourceId));

        return new MessageAndMetadata(
                json.getBytes(StandardCharsets.UTF_8),
                Map.of("contentType", "application/json"));
    }

    private boolean matchesResource(String json, UUID resourceId) {
        try {
            JsonNode node = objectMapper.readTree(json);
            return resourceId.toString().equals(node.path("resourceId").asText());
        } catch (Exception e) {
            return false;
        }
    }
}
