spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5434/booking
    username: booking_user
    password: booking_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  defer-datasource-initialization: true  # ensures Flyway runs migrations before Hibernate validates the schema

  kafka:
    bootstrap-servers: localhost:9092  # Kafka broker address
    consumer:
      group-id: booking-service        # consumer group — ensures each event is processed once per group
      auto-offset-reset: earliest      # read from beginning if no committed offset exists — important for cold start
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "leonil.sulude.catalog.dto"  # allow deserialization of Catalog DTOs
        spring.json.value.default.type: "leonil.sulude.booking.dto.ResourceCacheEventDTO"  # default deserialization target
server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      catalogService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      catalogService:
        maxAttempts: 3
        waitDuration: 500ms
  timelimiter:
    instances:
      catalogService:
        timeoutDuration: 2s

